import HomeOutlined from "@mui/icons-material/HomeOutlined";
import ArrowForwardIos from "@mui/icons-material/ArrowForwardIos";
import ArrowBackIos from "@mui/icons-material/ArrowBackIos";
import PeopleOutlined from "@mui/icons-material/PeopleOutlined";
import ReceiptOutlined from "@mui/icons-material/ReceiptOutlined";
import BarChartOutlined from "@mui/icons-material/BarChartOutlined";
import MapOutlined from "@mui/icons-material/MapOutlined";
import Groups from "@mui/icons-material/Groups";
import OndemandVideo from "@mui/icons-material/OndemandVideo";
import VideoCall from "@mui/icons-material/VideoCall";
import Web from "@mui/icons-material/Web";
import Quiz from "@mui/icons-material/Quiz";
import Wysiwyg from "@mui/icons-material/Wysiwyg";
import ManageHistory from "@mui/icons-material/ManageHistory";
import ExitToApp from "@mui/icons-material/ExitToApp";
import Menu from "@mui/icons-material/Menu";

export const HomeOutlinedIcon = HomeOutlined;
export const ArrowForwardIosIcon = ArrowForwardIos;
export const ArrowBackIosIcon = ArrowBackIos;
export const PeopleOutlinedIcon = PeopleOutlined;
export const ReceiptOutlinedIcon = ReceiptOutlined;
export const BarChartOutlinedIcon = BarChartOutlined;
export const MapOutlinedIcon = MapOutlined;
export const GroupsIcon = Groups;
export const OndemandVideoIcon = OndemandVideo;
export const VideoCallIcon = VideoCall;
export const WebIcon = Web;
export const QuizIcon = Quiz;
export const WysiwygIcon = Wysiwyg;
export const ManageHistoryIcon = ManageHistory;
export const ExitToAppIcon = ExitToApp;
export const MenuIcon = Menu;